### ISSUE TITLE
Interpreting test output

### ISSUE THREAD

**Issue by ebwinter95** [genepi/umi-pipeline-nf#65]
Hi, I am looking for some clarification in interpreting the output of the test data. I am seeing these directories within the output directory: barcode02/, barcode03/, freebayes/, and nextflow_stats/. But between barcode02/ vs. barcode03/, there are differences. Any information about why the barcode outputs are different would be greatly appreaciated.

test output directory:

barcode02/align/raw
barcode02/clustering/raw
barcode02/fastq_filtered/raw
barcode02/fastq_umi/raw
barcode02/stats/raw

barcode03/align/<consensus or raw or final>
barcode03/clustering/<consensus or raw>
barcode03/fastq/<consensus or final>
barcode03/fastq_filtered/raw
barcode03/fastq_umi/<consensus or raw>
barcode03/stats/<consensus or raw>

**Comment by AmstlerStephan** [comment]
Hi, 
Barcode02 does not have any clusters above the minimal number of reads per cluster threshold. Therefore there are no consensus reads created. 
Barcode03 contains 84 clusters above the threshold, for which the consensus is created and further processed. 

I am currently working on implementing nf-test for the whole pipeline, which also includes different, clearer test cases. 

I hope this helps to interpret the results.

**Comment by ebwinter95** [comment]
Thank you! That helps a lot
